require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/relax_sounds", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # RelaxSound. As you add validations to RelaxSound, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      RelaxSound.create! valid_attributes
      get relax_sounds_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      relax_sound = RelaxSound.create! valid_attributes
      get relax_sound_url(relax_sound)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_relax_sound_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      relax_sound = RelaxSound.create! valid_attributes
      get edit_relax_sound_url(relax_sound)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new RelaxSound" do
        expect {
          post relax_sounds_url, params: { relax_sound: valid_attributes }
        }.to change(RelaxSound, :count).by(1)
      end

      it "redirects to the created relax_sound" do
        post relax_sounds_url, params: { relax_sound: valid_attributes }
        expect(response).to redirect_to(relax_sound_url(RelaxSound.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new RelaxSound" do
        expect {
          post relax_sounds_url, params: { relax_sound: invalid_attributes }
        }.to change(RelaxSound, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post relax_sounds_url, params: { relax_sound: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested relax_sound" do
        relax_sound = RelaxSound.create! valid_attributes
        patch relax_sound_url(relax_sound), params: { relax_sound: new_attributes }
        relax_sound.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the relax_sound" do
        relax_sound = RelaxSound.create! valid_attributes
        patch relax_sound_url(relax_sound), params: { relax_sound: new_attributes }
        relax_sound.reload
        expect(response).to redirect_to(relax_sound_url(relax_sound))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        relax_sound = RelaxSound.create! valid_attributes
        patch relax_sound_url(relax_sound), params: { relax_sound: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested relax_sound" do
      relax_sound = RelaxSound.create! valid_attributes
      expect {
        delete relax_sound_url(relax_sound)
      }.to change(RelaxSound, :count).by(-1)
    end

    it "redirects to the relax_sounds list" do
      relax_sound = RelaxSound.create! valid_attributes
      delete relax_sound_url(relax_sound)
      expect(response).to redirect_to(relax_sounds_url)
    end
  end
end
